// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8DxJpVCduFtNpABbb7TrjDJBFWgQFha0',
    appId: '1:599122353739:web:11988691238ada6aadf7ce',
    messagingSenderId: '599122353739',
    projectId: 'storeup-9afa5',
    authDomain: 'storeup-9afa5.firebaseapp.com',
    databaseURL: 'https://storeup-9afa5-default-rtdb.firebaseio.com',
    storageBucket: 'storeup-9afa5.appspot.com',
    measurementId: 'G-SBM2PW8E38',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDni6GjwKCCoLZ6RKNP-KXWmBX4FVC6i2c',
    appId: '1:599122353739:android:8b7292692b725ef0adf7ce',
    messagingSenderId: '599122353739',
    projectId: 'storeup-9afa5',
    databaseURL: 'https://storeup-9afa5-default-rtdb.firebaseio.com',
    storageBucket: 'storeup-9afa5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWd6JYPlZZVyQLdKZJYdTaXYw-Ehekgtk',
    appId: '1:599122353739:ios:edc8b8a243147117adf7ce',
    messagingSenderId: '599122353739',
    projectId: 'storeup-9afa5',
    databaseURL: 'https://storeup-9afa5-default-rtdb.firebaseio.com',
    storageBucket: 'storeup-9afa5.appspot.com',
    androidClientId: '599122353739-0m3kblg0lf2fe3h06s3juvqpf7es12qp.apps.googleusercontent.com',
    iosClientId: '599122353739-u0cb9bcmg96o8g7oeqfpi4qej1tjoadh.apps.googleusercontent.com',
    iosBundleId: 'kr.storeup.userCore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWd6JYPlZZVyQLdKZJYdTaXYw-Ehekgtk',
    appId: '1:599122353739:ios:edc8b8a243147117adf7ce',
    messagingSenderId: '599122353739',
    projectId: 'storeup-9afa5',
    databaseURL: 'https://storeup-9afa5-default-rtdb.firebaseio.com',
    storageBucket: 'storeup-9afa5.appspot.com',
    androidClientId: '599122353739-0m3kblg0lf2fe3h06s3juvqpf7es12qp.apps.googleusercontent.com',
    iosClientId: '599122353739-u0cb9bcmg96o8g7oeqfpi4qej1tjoadh.apps.googleusercontent.com',
    iosBundleId: 'kr.storeup.userCore',
  );
}
