List<Map<String, String>> getBankData() {
  return [
    {'name': '경남은행', 'icon': 'bank/bank-kn', 'code': '39'},
    {'name': '광주은행', 'icon': 'bank/bank-gj', 'code': '34'},
    {'name': '단위농협(지역농축협)', 'icon': 'bank/bank-nh', 'code': '12'},
    // {'name': '대신증권', 'icon': 'ds'},
    // {'name': '메리츠증권', 'icon': 'meritz'},
    // {'name': '미래에셋증권', 'icon': 'mirae'},
    // {'name': '부국증권', 'icon': 'bg'},
    {'name': '부산은행', 'icon': 'bank/bank-bs', 'code': '32'},
    // {'name': '삼성증권', 'icon': 'ss'},
    {'name': '새마을금고', 'icon': 'bank/bank-smu', 'code': '45'},
    {'name': '산림조합', 'icon': 'bank/bank-sr', 'code': '64'},
    // {'name': '신영증권'},
    // {'name': '신한금융투자', 'icon': 'sh'},
    {'name': '신한은행', 'icon': 'bank/bank-sh', 'code': '88'},
    {'name': '신협', 'icon': 'bank/bank-sh-2', 'code': '48'},
    {'name': '씨티은행', 'icon': 'bank/bank-citi', 'code': '27'},
    {'name': '우리은행', 'icon': 'bank/bank-woori', 'code': '20'},
    {'name': '우체국', 'icon': 'bank/bank-post', 'code': '71'},
    // {'name': '유안타증권', 'icon': 'uanta'},
    // {'name': '유진투자증권', 'icon': 'ujin'},
    {'name': '저축은행중앙회', 'icon': 'bank/bank-juchuck', 'code': '50'},
    {'name': '전북은행', 'icon': 'bank/bank-jb', 'code': '37'},
    {'name': '제주은행', 'icon': 'bank/bank-sh', 'code': '35'},
    {'name': '카카오뱅크', 'icon': 'bank/bank-kakao', 'code': '90'},
    // {'name': '카카오페이증권', 'icon': 'kps'},
    {'name': '케이뱅크', 'icon': 'bank/bank-k', 'code': '89'},
    // {'name': '키움증권', 'icon': 'kium'},
    {'name': '토스뱅크', 'icon': 'bank/bank-tb', 'code': '92'},
    // {'name': '토스증권', 'icon': 'ts'},
    // {'name': '펀드온라인코리아(한국포스증권)', 'icon': 'bank/bank-fok', },
    // {'name': '하나금융투자'},
    {'name': '하나은행', 'icon': 'bank/bank-hana', 'code': '81'},
    // {'name': '하이투자증권', 'icon': 'hi'},
    // {'name': '한국투자증권', 'icon': 'hts'},
    // {'name': '한화투자증권', 'icon': 'hts-2'},
    // {'name': '현대차증권', 'icon': 'hcs'},
    {'name': '홍콩상하이은행', 'icon': 'bank/bank-hsb', 'code': '54'},
    // {'name': 'DB금융투자', 'icon': 'db'},
    {'name': 'DGB대구은행', 'icon': 'bank/bank-dgb', 'code': '31'},
    {'name': 'IBK기업은행', 'icon': 'bank/bank-ibk', 'code': '03'},
    {'name': 'KB국민은행', 'icon': 'bank/bank-kb', 'code': '06'},
    // {'name': 'KB증권', 'icon': 'kbs'},
    {'name': 'KDB산업은행', 'icon': 'bank/bank-kdb', 'code': '02'},
    // {'name': 'KTB투자증권(다올투자증권)', 'icon': 'ktb'},
    // {'name': 'LIG투자증권', 'icon': 'cape'},
    {'name': 'NH농협은행', 'icon': 'bank/bank-nh', 'code': '11'},
    // {'name': 'NH투자증권', 'icon': 'nhts'},
    {'name': 'SC제일은행', 'icon': 'bank/bank-sc', 'code': '23'},
    {'name': 'SH수협은행', 'icon': 'bank/bank-sh-3', 'code': '07'},
    // {'name': 'SK증권', 'icon': 'sks'}
  ];
}
